name: Monorepo

on: push

env:
  CI: 'true'
  AWS_SDK_LOAD_CONFIG: 'true'
  AWS_REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2
  RELEASE_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install
        env:
          REALM: dev
          ENV: staging
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ${AWS_ACCESS_KEY_ID} | sed 's/./& /g'
          aws s3 ls
          aws sts get-caller-identity
          echo npm ci

      # - name: Build and Test (non-master)
      #   if: github.ref != 'refs/heads/master'
      #   run: |
      #     npm test -- --since origin/master

      # - name: Build and Test (master)
      #   if: github.ref == 'refs/heads/master'
      #   env:
      #     REALM: dev
      #     ENV: staging
      #   run: |
      #     npm test -- --since $(git rev-parse HEAD~1)

  deploy-dev-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install wheel
          pip3 install aws-sam-cli
          export PATH=/home/runner/.local/bin:$PATH
          sam --version
          npm ci

      - name: Deploy to dev staging
        env:
          REALM: dev
          ENV: staging
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export PATH=/home/runner/.local/bin:$PATH
          npm run deploy -- --since $(git rev-parse HEAD~1)

  deploy-prod-green:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: install
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install wheel
          pip3 install aws-sam-cli
          export PATH=/home/runner/.local/bin:$PATH
          sam --version
          npm ci

      - name: Deploy to prod green
        env:
          REALM: prod
          ENV: green
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export PATH=/home/runner/.local/bin:$PATH
          npm run deploy -- --since $(git rev-parse HEAD~1)
