name: Test

on: push

env:
  CI: 'true'
  AWS_SDK_LOAD_CONFIG: 'true'
  AWS_REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2
  RELEASE_VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install
        run: |
          whoami
          pip --version
          pip3 --version
          # curl https://bootstrap.pypa.io/get-pip.py | sudo python3
          pip3 install --upgrade setuptools pip
          # pip3 --version
          # which pip3
          # which python3
          python3 -m site
          pip3 install wheel
          # python3 setup.py bdist_wheel
          pip3 list -v
          echo $PATH

          # sudo apt update
          # sudo apt-get install python3-setuptools

          pip3 install aws-sam-cli
          pip3 list -v
          export PATH=/home/runner/.local/bin:$PATH
          sam --version || true

# pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
# pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
